[package]
name = "arbitors"
version = "0.1.0"
edition = "2021"
authors = ["Craig Warner"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]